name: menulibre
base: core24 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: MenuLibre is an advanced FreeDesktop.org compliant menu editor.
description: |
  MenuLibre is an advanced menu editor with modern features in a clean, easy-to-use interface. It lets you :
    --> Create new launchers or modify existing ones with complete control and access to hidden settings
    --> Add and adjust desktop actions: shortcuts to advanced application features
    --> Easily rearrange the menu to suit your tastes
icon: snap/gui/menulibre.svg
grade: stable
confinement: classic

apps:
  menulibre:
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      GI_TYPELIB_PATH: $SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0
      GTK_IM_MODULE_FILE: /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0
    command: bin/menulibre
    
parts:
  menulibre:
    plugin: python
    source: https://github.com/bluesabre/menulibre.git
    build-packages:
      - gir1.2-gtk-3.0
      - intltool
      - libgnome-menu-3-dev
      - python-gi-dev
      - python3
      - python3-distutils-extra
      - python3-psutil
    stage-packages:
      - gir1.2-gdkpixbuf-2.0
      - gir1.2-glib-2.0
      - gir1.2-gmenu-3.0
      - gir1.2-gtk-3.0
      - gir1.2-gtksource-3.0
      - gnome-menus
      - python3
      - python3-gi
      - python3-psutil
      - xdg-utils
    build-attributes:
      - enable-patchelf
    override-build: |
      python3 setup.py build
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -r /root/parts/menulibre/build/bin/* $SNAPCRAFT_PART_INSTALL/bin/
      cp -r /root/parts/menulibre/build/* $SNAPCRAFT_PART_INSTALL/
